XPATH_LOG_BTN = '//*[@id="react-root"]/section/main/div/article/div/div[1]/div/form/span/button'
XPATH_NEW_FIRST_PHOTO = '//*[@id="react-root"]/section/main/article/div[2]/div[1]/div[1]/a[1]/div'
#XPATH_NEW_FIRST_PHOTO = '/html/body/div[2]/div/div[2]/div/article/div[2]/section[1]/a[1]/span'
XPATH_USERNAME = '/html/body/div[2]/div/div[2]/div/article/header/div/a'
XPATH_LIKE_BTN = '/html/body/div[2]/div/div[2]/div/article/div[2]/section[2]/a/span'
#XPATH_LIKE_BTN = '/html/body/div[2]/div/div[2]/div/article/div[2]/section[1]/a[1]/span'
XPATH_NEXT_BTN = '/html/body/div[2]/div/div[1]/div/div/a[2]'

XPATH_FIRST_PHOTO_ON_ACCOUNT = '//*[@id="react-root"]/section/main/article/div/div[1]/div[1]/a[1]/div'
XPATH_LIKE_ON_ACCOUNT_BTN = '/html/body/div[2]/div/div[2]/div/article/div[2]/section[2]/a/span'
XPATH_NEXT_FIRST_ON_ACCOUNT_BTN = '/html/body/div[2]/div/div[1]/div/div/a'
XPATH_NEXT_ON_ACCOUNT_BTN = '/html/body/div[2]/div/div[1]/div/div/a[2]'
XPATH_FOLLOW_ON_PHOTO_ON_ACCOUNT_BTN = '/html/body/div[2]/div/div[2]/div/article/header/span/button'

XPATH_FOLLOWERS_BTN = '//*[@id="react-root"]/section/main/article/header/div[2]/ul/li[3]/a'
XPATH_UNFOLLOW_BTN = '/html/body/div[2]/div/div[2]/div/div[2]/ul/li[button_number]/div/div[2]/span/button'